version: '3'
services:
  frontend:
    ports:
      - 80:80
    image: ddarahakit2023/frontend:1.0
    depends_on:
      - backend
    environment:
      BACKEND_URL: backend
  backend:
    image: ddarahakit2023/backend:1.0
    ports:
      - 8080:8080
    environment:
      AWS_ACCESS_KEY: AKIA5BAYKHGOCIT4G6T7
      AWS_BUCKET_NAME: gurigiri-s3
      AWS_REGION_NAME: ap-northeast-2
      AWS_SECRET_KEY: n2iva/ZOtGPGXG43uthnppcDcRLch8LVMyJHBLPO
      DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DB_USERNAME: admin
      DB_PASSWORD: qwer1234
      DB_URL: jdbc:mysql://database-1.cddutvfrnx3q.ap-northeast-2.rds.amazonaws.com:3306/test
      IAMPORT_KEY: 1861881235228725
      IAMPORT_SECRET: z74Jn4UxTEJZulLFebu6jpgEH1ag6MPLst9lSfhCBUrSMQdUKPJpMIFQxTh0nUrwHQ068s08JUuSgPda
      JWT_EXPIRED_TIME: 18000000
      JWT_SECRET: abcdefghijklmnopqrstuvwxyz0123456789
      MAIL_HOST: smtp.gmail.com
      MAIL_PASSWORD: bngtyvtnwxiwutif
      MAIL_PORT: 587
      MAIL_USERNAME: ell950404
